### ISSUE TITLE
Wrong stencils in UI

### ISSUE THREAD

**Issue by vguerci** [davidmorford/iOSDesignStencils#1]
Great job with your iPhone/iPad stencils, exactly the kind of thing I was searching :)

But... I first found them on graffletopia... Then figured you did a github repo! great! and with a newest version! wonderful... watching repo... :)

But unfortunatly you have commited the wrong files in

```
iOSDesignStencils / Stencils / iOS Design / UI
```

These (<500KB) are the wireframes one and not the full color ones I wanted to use...
Rolling back to 1.3 from graffletopia waiting you to fix :)

---

Off-topic, what's your suggestion to use em with iPad version? Adding the gstencil file works, but they show up as a document too... Weird.

Thanks again,
Vincent.

**Comment by davidmorford** [comment]
Thanks for the pointing that out! I compared and copied the .gstencil files from the wrong directory. Fixes have been pushed to repo and download zips will be updated shortly.

**Comment by vguerci** [comment]
better now :)
thanks for the (very quick) fix

**Comment by davidmorford** [comment]
No worries. Love seeing and hearing about the stencils being used for any kind of apps.
